### ISSUE TITLE
[BUG] kustomize release fetch fails

### ISSUE THREAD

**Issue by hefekranz** [karancode/kustomize-github-action#25]
**Describe the bug**
Hey Karan, thanks for this tool.

As of this morning, the action, with defaults, fails. After some investigation i found out that the problem lies in the default kustomize version v3.0.0 or should we say the kustomize release process :)

https://github.com/karancode/kustomize-github-action/blob/57c6d56a5fb40a3b5e7c8001f21edd63afe3e05c/src/entrypoint.sh#L40

The problem here is that v3.0.0 is not included in the first 100 results anymore and thats the max per_page github allows.

Not sure whats the best solution here, but maybe you should pull up the default kustomize version :man_shrugging: 

Cheers from Stuttgart,
Levin

**To Reproduce**
`curl -s "https://api.github.com/repos/kubernetes-sigs/kustomize/releases?per_page=200" | jq -r '.[].assets[] | select(.browser_download_url | test("kustomize(_|.)?(v)?'3.0.0'_linux_amd64"))'`

**Comment by karancode** [comment]
@hefekranz (Sorry for replying late here). Thanks alot for reporting this. I will check if I can find a way to support more older versions 🤔

**Comment by karancode** [comment]
Hello @hefekranz, I have added a hack fix #28 for this to avoid crashes for now. I will work on a proper solution later on. Please use latest version `v1.2.1`.
Thanks again for reporting. 

PS: PRs are welcome if you want to give it a shot! 🙇🏼

**Comment by dteoh** [comment]
I'm wondering if it would be more straightforward to hardcode the download URL as a template instead of paging through the releases API? Homebrew does a similar thing.

**Comment by karancode** [comment]
fixed in #29. Thanks guys. Please use `@master` or `@v1.2.2`.
