### ISSUE TITLE
curl: no URL specified!

### ISSUE THREAD

**Issue by Nurlan199206** [karancode/kustomize-github-action#27]
how to bypass this error? help pls

Run karancode/kustomize-github-action@master
/usr/bin/docker run --name e4fec0ae5cb17f4da89857f83af869fcd5_e30b9e --label 5588e4 --workdir /github/workspace --rm -e IMAGE_NAME -e GITHUB_ACCESS_TOKEN -e INPUT_KUSTOMIZE_VERSION -e INPUT_KUSTOMIZE_BUILD_DIR -e INPUT_KUSTOMIZE_COMMENT -e INPUT_KUSTOMIZE_OUTPUT_FILE -e INPUT_KUSTOMIZE_BUILD_OPTIONS -e INPUT_ENABLE_ALPHA_PLUGINS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/test1/test1":"/github/workspace" 5588e4:fec0ae5cb17f4da89857f83af869fcd5
Downloading kustomize v3.0.0
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
Failed to download kustomize v3.0.0.

**Comment by karancode** [comment]
hello @Nurlan199206 apologize for this. This was already reported https://github.com/karancode/kustomize-github-action/issues/25 and it is happening because `v3.0.0` is not present in the first 100 results and thats the max per_page that github allows. 

I will check a way to handle this! 🙇🏼

**Comment by karancode** [comment]
Hello @Nurlan199206 I have added a hack fix to address this problem. Please use `@master` or use latest version `v1.2.1`.
I will work on having a proper fix for this later on. Thank you.! 🙇🏼
