### ISSUE TITLE
tar: invalid magic, tar: short read, Failed to download kustomize v3.8.1

### ISSUE THREAD

**Issue by kalyanteja19** [karancode/kustomize-github-action#36]
**Describe the bug**
We are getting the below error.

tar: invalid magic, 
tar: short read, 
Failed to download kustomize v3.8.1

**To Reproduce**
![image](https://user-images.githubusercontent.com/53315599/193289661-a0d81c7b-39f4-4386-8dc4-38beee28c2f0.png)
**Expected behavior**

**Screenshots/Actions log**
It should download kustomize and run properly

**Running on:**
ubuntu-latest

**Additional context**

**Comment by karancode** [comment]
Hi @kalyanteja19 I tried with this specific version and it is working fine. Could you please try again with the latest action version `@v1.3.0` or `@master`? Thanks!

**Comment by kalyanteja19** [comment]
> Hi @kalyanteja19 I tried with this specific version and it is working fine. Could you please try again with the latest action version `@v1.3.0` or `@master`? Thanks!

Thank you. this is intermittent issue.
