### ISSUE TITLE
Consider output to file in addition to outputs?

### ISSUE THREAD

**Issue by marccampbell** [karancode/kustomize-github-action#9]
I have to have an additional step in all workflows using this to write the output to a file, and it loses the new lines from the built output when I do.

Would you be open to a PR that adds a new input that, if set, this action will write the contents of the built output to this file?

**Comment by karancode** [comment]
@marccampbell Thanks for reporting it (& the PR).
But why do you need the output in a file ? And how do you plan to use it ?

**Comment by Kampe** [comment]
I second this, I need to write to a file, or atleast have the output be in a useable format.  As like OP said, it loses all new lines due to no quotes.

**Comment by Kampe** [comment]
Look into gitops, this is a very common pattern for use with Kustomize - write out a file to another manifest repository and push the changes back to git

**Comment by karancode** [comment]
From gitops pov, it makes sense. Thank you guys @Kampe @marccampbell

**Comment by karancode** [comment]
Closing as #10 is merged! 🍻
